# _config.yml

title: "Jason's Blog"
description: >-
  一个由 Jekyll 驱动的，关于技术与生活的个人博客。
baseurl: ""
url: "https://ZhuXunJason.github.io"
github_username: ZhuXunJason

markdown: kramdown
plugins:
  - jekyll-feed

# 定义集合
collections:
  academic:
    output: true
    permalink: /academic/:name
  life:
    output: true
    permalink: /life/:name

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/

# Sass 配置
sass:
  sass_dir: _sass
  style: compressed  # 在构建时自动压缩CSS
